### ISSUE TITLE
Come up with a template for the documents

### ISSUE THREAD

**Issue by osamaramihafez** [Quran-Journey/parsing#1]
The document template MUST take into account the following TODOs:

- [x] Quran-Journey/parsing#6  
- [x] Quran-Journey/parsing#2  
- [ ] Quran-Journey/parsing#3 
- [ ] Quran-Journey/parsing#4 
- [ ] Quran-Journey/parsing#5 

Remember to:
- Parse any subcategories
- Follow a reliable structure (i.e. how verses are split up and presented)
